### ISSUE TITLE
error to deploy the stack

### ISSUE THREAD

**Issue by thiagocpv** [jcwimer/docker-swarm-autoscaler#4]
On debian bullseye with swarm, I got the error below:

_Cannot detect current cgroup on cgroup v2_

How can I solve this?

Thanks.
Thiago

**Comment by jcwimer** [comment]
This looks to be a cadvisor is or issue: https://github.com/google/cadvisor/issues/3073

Please follow along there.

**Comment by thiagocpv** [comment]
Yeah, I am in there. Following.
Thanks.

**Comment by jcwimer** [comment]
Issue was with cadvisor
